//
// Created by ishaa on 29-03-2026.
//

#ifndef DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_EULER_TOTIENT_H
#define DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_EULER_TOTIENT_H


class euler_totient {
};


#endif //DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_EULER_TOTIENT_H