//
// Created by ishaa on 29-03-2026.
//

#ifndef DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_NCR_H
#define DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_NCR_H


class ncr {
};


#endif //DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_NCR_H