//
// Created by ishaa on 19-03-2026.
//

#ifndef DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_FIXED_SIZE_H
#define DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_FIXED_SIZE_H


class fixed_size {
};


#endif //DSA_STRUCTURES_AND_ALGO_IMPLEMENTATIONS_FIXED_SIZE_H